# This Dockerfile is not to be used in production!
# It serves for development and testing purposes only.
version: '3.8'

services:
  web:
    build: .
    ports:
          - "${SECURE_WEB_PORT}:443"
    depends_on:
      - db
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #This database does not need volumes. Data shall not be persisted.
  #  Tests are carried out with fresh data on every run.
  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: --general-log --general-log-file=/var/lib/mysql/general.log
