# This Dockerfile is not to be used in production!
# It serves for development and testing purposes only.
version: '3.8'

services:
  web:
    build: .
    ports:
            #- "${WEB_PORT}:80"
            #- "${SECURE_WEB_PORT}:443"
      - "8443:443"
    depends_on:
      - db
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      #    ports:
            #- "${DB_PORT}:3306"
    volumes:
      - /home/git/scripts/my.cnf:/etc/mysql/conf.d/my.cnf
