<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-11-18 at 21:36:38.
 */
class employeeTest extends PHPUnit_Framework_TestCase {

    /**
     * @var employee
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $employee_id = 5;
        $last_name = 'Maier';
        $first_name = 'Ma';
        $working_week_hours = 40;
        $lunch_break_minutes = 30;
        $profession = 'Apotheker';
        $branch = 1;
        $start_of_employment = '2015-01-01';
        $end_of_employment = NULL;
        $holidays = 28;
        $this->object = new employee($employee_id, $last_name, $first_name, $working_week_hours, $lunch_break_minutes, $profession, $branch, $start_of_employment, $end_of_employment, $holidays);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    public function testread_principle_roster_from_database() {
        $Principle_roster = $this->object->Principle_roster;
        $Principle_roster_hash = sha1(json_encode($Principle_roster));
        $Principle_roster_hash_should = '20dd88216dc10d174a2c73d073bc9fc86a2152b7';
        $this->assertTrue($Principle_roster_hash_should === $Principle_roster_hash);
    }

    public function testread_working_week_days_from_database() {
        $working_week_days = $this->object->working_week_days;
        $this->assertTrue(5 === $working_week_days);
    }

}
