<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-11-18 at 21:36:38.
 */
class employeeTest extends PHPUnit_Framework_TestCase {

    /**
     * @var employee
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $employee_id = 5;
        $last_name = 'Maier';
        $first_name = 'Ma';
        $working_week_hours = 40;
        $lunch_break_minutes = 30;
        $profession = 'Apotheker';
        $branch = 1;
        $start_of_employment = '2015-01-01';
        $end_of_employment = NULL;
        $holidays = 28;
        $this->object = new employee($employee_id, $last_name, $first_name, $working_week_hours, $lunch_break_minutes, $profession, $branch, $start_of_employment, $end_of_employment, $holidays);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    public function testread_principle_roster_from_database() {
        $date_object = new DateTime('this wednesday');
        $Principle_roster = $this->object->get_principle_roster_on_date($date_object);
        $weekday = $Principle_roster[$date_object->getTimestamp()][0]->weekday;
        $this->assertEquals('2', $weekday);

        $duty_start_sql = $Principle_roster[$date_object->getTimestamp()][0]->__get('duty_start_sql');
        $this->assertEquals('11:00', $duty_start_sql);

        $duty_end_sql = $Principle_roster[$date_object->getTimestamp()][0]->__get('duty_end_sql');
        $this->assertEquals('20:00', $duty_end_sql);
    }

}
