<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-11-21 at 21:53:40.
 */
class user_dialogTest extends PHPUnit_Framework_TestCase {

    /**
     * @var user_dialog
     */
    protected
            $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = $this->getMockForAbstractClass('user_dialog');
        //$this->object = createMock('user_dialog');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers user_dialog::build_messages
     * @todo   Implement testBuild_messages().
     */
    public function testBuild_messages() {
// Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers user_dialog::build_messages_for_cli
     * @todo   Implement testBuild_messages_for_cli().
     */
    public function testBuild_messages_for_cli() {
// Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers user_dialog::add_message
     * @todo   Implement testAdd_message().
     */
    public function testAdd_message() {
// Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers user_dialog::build_contact_form
     * @todo   Implement testBuild_contact_form().
     */
    public function testBuild_contact_form() {
// Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers user_dialog::contact_form_send_mail
     * @todo   Implement testContact_form_send_mail().
     */
    public function testContact_form_send_mail() {
// Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers user_dialog::contact_form_send_mail_build_message
     * @todo   Implement testContact_form_send_mail_build_message().
     */
    public function testContact_form_send_mail_build_message() {
// Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers user_dialog::contact_form_send_mail_build_header
     * @todo   Implement testContact_form_send_mail_build_header().
     */
    public function testContact_form_send_mail_build_header() {
// Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
